<div class="container content">
    <div>
        <form id="search-video" class="form-inline">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
    <div class="video-content">
    </div>
</div>
<script>
    $('#search-video').submit(function (){
        event.preventDefault();
        if($('#search-video>input').val() != null && $('#search-video>input').val() != '') {
            var string = $('#search-video>input').val();
            $.ajax({
                type: "POST",
                url: "/youtubeapplication/index",
                data: JSON.stringify({search: string}),
                data: {search: string},
                dataType: 'json',
                success: function (data) {
                    var videoData = data.data.items;
                    console.log(videoData);
                    for(var x in videoData){
                        for (var y in videoData[x].id){
                            var videoIdentification = videoData[x].id.videoId;
                            $('.video-content').append('<iframe width=100% height="315" src="https://www.youtube.com/embed/' +
                                videoIdentification + ' frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>');
                        }
                    }
                },
                error: function (data) {
                    alert('error');
                }
            });
        }
    });
</script>
